on:
  push:
    tags:
    - 'v*'

name: Upload Release Assets

jobs:
  build:
    name: Upload Release Assets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Get Version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
        
      - name: Build Dashboard 🔧
        run: |
          ./install-dependencies.sh
          ./build-dashboard.sh
          
      - name: Set up Python
        uses: actions/setup-python@v1
      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install platformio
    
      - name: Build PlatformIO Binaries
        run: |
          platformio run -e esp8266-pxmatrix-4mb-32x64 -e esp32-pxmatrix-4mb-32x64 -e esp8266-ssd1306-4mb-128x64
          platformio run -e esp8266-pxmatrix-4mb-32x64 -e esp32-pxmatrix-4mb-32x64 -t buildfs
          mv ./.pio/build/esp8266-ssd1306-4mb-128x64/firmware.bin ./firmware-esp8266-ssd1306-4mb-128x64-${{ steps.get_version.outputs.VERSION }}.bin
          mv ./.pio/build/esp8266-pxmatrix-4mb-32x64/firmware.bin ./firmware-esp8266-pxmatrix-4mb-32x64-${{ steps.get_version.outputs.VERSION }}.bin
          mv ./.pio/build/esp32-pxmatrix-4mb-32x64/firmware.bin ./firmware-esp32-pxmatrix-4mb-32x64-${{ steps.get_version.outputs.VERSION }}.bin
          mv ./.pio/build/esp8266-pxmatrix-4mb-32x64/littlefs.bin ./fs-esp8266-${{ steps.get_version.outputs.VERSION }}.bin
          mv ./.pio/build/esp32-pxmatrix-4mb-32x64/spiffs.bin ./fs-esp32-${{ steps.get_version.outputs.VERSION }}.bin
          ./combine-binaries-esp8266.sh firmware-esp8266-ssd1306-4mb-128x64-${{ steps.get_version.outputs.VERSION }}.bin fs-esp8266-${{ steps.get_version.outputs.VERSION }}.bin ./esp8266-ssd1306-4mb-128x64-${{ steps.get_version.outputs.VERSION }}.bin
          ./combine-binaries-esp8266.sh firmware-esp8266-pxmatrix-4mb-32x64-${{ steps.get_version.outputs.VERSION }}.bin fs-esp8266-${{ steps.get_version.outputs.VERSION }}.bin ./esp8266-pxmatrix-4mb-32x64-${{ steps.get_version.outputs.VERSION }}.bin
          ./combine-binaries-esp32.sh firmware-esp32-pxmatrix-4mb-32x64-${{ steps.get_version.outputs.VERSION }}.bin fs-esp32-${{ steps.get_version.outputs.VERSION }}.bin esp32-pxmatrix-4mb-32x64-${{ steps.get_version.outputs.VERSION }}.bin
          
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      
      - name: Upload Binaries
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          hub release edit -a ./firmware-esp8266-ssd1306-4mb-128x64-${{ steps.get_version.outputs.VERSION }}.bin -m "" ${{ steps.get_version.outputs.VERSION }}
          hub release edit -a esp8266-ssd1306-4mb-128x64-${{ steps.get_version.outputs.VERSION }}.bin -m "" ${{ steps.get_version.outputs.VERSION }}
          hub release edit -a ./firmware-esp8266-pxmatrix-4mb-32x64-${{ steps.get_version.outputs.VERSION }}.bin -m "" ${{ steps.get_version.outputs.VERSION }}
          hub release edit -a esp8266-pxmatrix-4mb-32x64-${{ steps.get_version.outputs.VERSION }}.bin -m "" ${{ steps.get_version.outputs.VERSION }}
          hub release edit -a ./firmware-esp32-pxmatrix-4mb-32x64-${{ steps.get_version.outputs.VERSION }}.bin -m "" ${{ steps.get_version.outputs.VERSION }}
          hub release edit -a esp32-pxmatrix-4mb-32x64-${{ steps.get_version.outputs.VERSION }}.bin -m "" ${{ steps.get_version.outputs.VERSION }}
          hub release edit -a ./fs-esp32-${{ steps.get_version.outputs.VERSION }}.bin -m "" ${{ steps.get_version.outputs.VERSION }}
          hub release edit -a ./fs-esp8266-${{ steps.get_version.outputs.VERSION }}.bin -m "" ${{ steps.get_version.outputs.VERSION }}
