on:
  push:
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Upload Release Assets

jobs:
  build:
    name: Upload Release Assets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Get Version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
        
      - name: Build Dashboard 🔧
        run: |
          ./install-dependencies.sh
          ./build-dashboard.sh
          
      - name: Set up Python
        uses: actions/setup-python@v1
      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install platformio
    
      - name: Build PlatformIO Binaries
        run: |
          platformio run -e nodemcuv2-32x64 -e d1-mini-32x64
          platformio run -e nodemcuv2-32x64 -e d1-mini-32x64 -t buildfs
          mv ./.pio/build/nodemcuv2-32x64/firmware.bin ./firmware-nodemcuv2-32x64-${{ steps.get_version.outputs.VERSION }}.bin
          mv ./.pio/build/d1-mini-32x64/firmware.bin ./firmware-d1-mini-32x64-${{ steps.get_version.outputs.VERSION }}.bin
          mv ./.pio/build/nodemcuv2-32x64/littlefs.bin ./fs-4m-${{ steps.get_version.outputs.VERSION }}.bin
          ./combine-binaries.sh firmware-nodemcuv2-32x64-${{ steps.get_version.outputs.VERSION }}.bin empty.bin fs-4m-${{ steps.get_version.outputs.VERSION }}.bin nodemcuv2-32x64-${{ steps.get_version.outputs.VERSION }}.bin
          ./combine-binaries.sh firmware-d1-mini-32x64-${{ steps.get_version.outputs.VERSION }}.bin empty.bin fs-4m-${{ steps.get_version.outputs.VERSION }}.bin d1-mini-32x64-${{ steps.get_version.outputs.VERSION }}.bin
          
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      
      - name: Upload Binaries
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          hub release edit -a ./firmware-nodemcuv2-32x64-${{ steps.get_version.outputs.VERSION }}.bin -m "" ${{ steps.get_version.outputs.VERSION }}
          hub release edit -a nodemcuv2-32x64-${{ steps.get_version.outputs.VERSION }}.bin -m "" ${{ steps.get_version.outputs.VERSION }}
          hub release edit -a ./firmware-d1-mini-32x64-${{ steps.get_version.outputs.VERSION }}.bin -m "" ${{ steps.get_version.outputs.VERSION }}
          hub release edit -a d1-mini-32x64-${{ steps.get_version.outputs.VERSION }}.bin -m "" ${{ steps.get_version.outputs.VERSION }}
          hub release edit -a ./fs-4m-${{ steps.get_version.outputs.VERSION }}.bin -m "" ${{ steps.get_version.outputs.VERSION }}
